# Generated by Django 5.2.7 on 2025-10-06 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('locality', models.CharField(blank=True, max_length=100, null=True)),
                ('area_m2', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=100)),
                ('gas', models.CharField(max_length=30)),
                ('factor_value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('source_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('year_applic', models.PositiveIntegerField(blank=True, null=True)),
                ('gwp_100yr', models.FloatField(blank=True, null=True)),
                ('uncertainty_pct', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtinguisherType',
            fields=[
                ('ext_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('gwp_100yr', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('fuel_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaperWeightCatalog',
            fields=[
                ('size', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('kg_per_ream', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('waste_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('unit_default', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='carbon_footprint.emissioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PaperConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reams', models.PositiveIntegerField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_records', to='carbon_footprint.campus')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paper_usages', to='carbon_footprint.paperweightcatalog')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_records', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='NaturalGasConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
                ('m3', models.FloatField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_records', to='carbon_footprint.campus')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_records', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='FuelConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallons', models.FloatField()),
                ('biogenic_co2', models.FloatField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='carbon_footprint.campus')),
                ('fuel_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_consumptions', to='carbon_footprint.fueltype')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_date', models.DateField()),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('co2_kg', models.FloatField()),
                ('roundtrip', models.BooleanField(default=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='FieldPracticeTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('km_oneway', models.FloatField()),
                ('total_km', models.FloatField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_trips', to='carbon_footprint.campus')),
                ('fuel_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practice_trips', to='carbon_footprint.fueltype')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_trips', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='ExtinguisherRefill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_kg', models.FloatField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extinguisher_refills', to='carbon_footprint.campus')),
                ('ext_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refills', to='carbon_footprint.extinguishertype')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extinguisher_refills', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(blank=True, max_length=100, null=True)),
                ('kwh', models.FloatField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_records', to='carbon_footprint.campus')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_records', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedGoodsServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_service', models.CharField(max_length=150)),
                ('amount', models.FloatField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_records', to='carbon_footprint.campus')),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='carbon_footprint.emissionfactor')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_records', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='RemovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtype', models.CharField(max_length=100)),
                ('tco2e', models.FloatField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_records', to='carbon_footprint.campus')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_records', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleFleetConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_traveled', models.FloatField()),
                ('gallons', models.FloatField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_records', to='carbon_footprint.campus')),
                ('fuel_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_fleet_consumptions', to='carbon_footprint.fueltype')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_records', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.FloatField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_records', to='carbon_footprint.campus')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_records', to='carbon_footprint.period')),
                ('waste_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_records', to='carbon_footprint.wastetype')),
            ],
        ),
    ]
