# Generated by Django 5.2.8 on 2025-11-07 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('locality', models.CharField(blank=True, max_length=100, null=True)),
                ('area_m2', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtinguisherType',
            fields=[
                ('ext_code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('gwp_100yr', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('fuel_code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaperWeightCatalog',
            fields=[
                ('size', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('kg_per_ream', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('waste_code', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('treatment', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('unit_default', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='carbon_footprint.emissioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=100)),
                ('gas', models.CharField(max_length=30)),
                ('factor_value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('gwp_100yr', models.FloatField(blank=True, null=True)),
                ('source_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('year_applic', models.PositiveIntegerField(blank=True, null=True)),
                ('uncertainty_pct', models.FloatField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='carbon_footprint.emissionsource')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PaperConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reams', models.PositiveIntegerField()),
                ('total_tco2e', models.FloatField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_records', to='carbon_footprint.campus')),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_usages', to='carbon_footprint.emissionfactor')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paper_usages', to='carbon_footprint.paperweightcatalog')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_records', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='NaturalGasConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m3', models.FloatField()),
                ('total_tco2e', models.FloatField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_records', to='carbon_footprint.campus')),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gas_usages', to='carbon_footprint.emissionfactor')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gas_usages', to='carbon_footprint.fueltype')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_records', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='LubricantConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('unit', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('total_tco2e', models.FloatField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lubricant_records', to='carbon_footprint.campus')),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lubricant_usages', to='carbon_footprint.emissionfactor')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lubricant_records', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='LodgingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('nights', models.FloatField()),
                ('total_tco2e', models.FloatField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodging_records', to='carbon_footprint.campus')),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lodging_usages', to='carbon_footprint.emissionfactor')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodging_records', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='IndustrialProcessEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('process_type', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
                ('activity', models.FloatField()),
                ('total_tco2e', models.FloatField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industrial_processes', to='carbon_footprint.campus')),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industrial_processes', to='carbon_footprint.emissionfactor')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industrial_processes', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='GroundTransportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('total_tco2e', models.FloatField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ground_transports', to='carbon_footprint.campus')),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ground_transports', to='carbon_footprint.emissionfactor')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ground_transports', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='FuelConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('unit', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('scope', models.CharField(choices=[('stationary', 'Fuente estacionaria')], default='stationary', max_length=20)),
                ('total_tco2e', models.FloatField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='carbon_footprint.campus')),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_consumptions', to='carbon_footprint.emissionfactor')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_consumptions', to='carbon_footprint.fueltype')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_records', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('passengers', models.PositiveIntegerField(default=1)),
                ('km', models.FloatField(blank=True, null=True)),
                ('total_tco2e', models.FloatField(blank=True, null=True)),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_usages', to='carbon_footprint.emissionfactor')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='FieldPracticeTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('km_oneway', models.FloatField()),
                ('total_km', models.FloatField()),
                ('total_tco2e', models.FloatField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_trips', to='carbon_footprint.campus')),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_trips', to='carbon_footprint.emissionfactor')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_trips', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='ExtinguisherRefill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('amount', models.FloatField()),
                ('total_tco2e', models.FloatField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extinguisher_refills', to='carbon_footprint.campus')),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extinguisher_usages', to='carbon_footprint.emissionfactor')),
                ('ext_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refills', to='carbon_footprint.extinguishertype')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extinguisher_refills', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_label', models.CharField(blank=True, max_length=50, null=True)),
                ('is_biogenic', models.BooleanField(default=False)),
                ('total_tco2e', models.FloatField()),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='carbon_footprint.campus')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='carbon_footprint.emissioncategory')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('kwh', models.FloatField()),
                ('total_tco2e', models.FloatField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_records', to='carbon_footprint.campus')),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electricity_usages', to='carbon_footprint.emissionfactor')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_records', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='RemovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtype', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('tco2e', models.FloatField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_records', to='carbon_footprint.campus')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_records', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleFleetConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('unit', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('km_traveled', models.FloatField(blank=True, null=True)),
                ('total_tco2e', models.FloatField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_records', to='carbon_footprint.campus')),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_consumptions', to='carbon_footprint.emissionfactor')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_fleet_consumptions', to='carbon_footprint.fueltype')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_records', to='carbon_footprint.period')),
            ],
        ),
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('amount', models.FloatField()),
                ('total_tco2e', models.FloatField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_records', to='carbon_footprint.campus')),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_usages', to='carbon_footprint.emissionfactor')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_records', to='carbon_footprint.period')),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_records', to='carbon_footprint.wastetype')),
            ],
        ),
        migrations.AddIndex(
            model_name='emissionfactor',
            index=models.Index(fields=['agent', 'gas', 'unit', 'year_applic'], name='carbon_foot_agent_e1cc4a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emissionsummary',
            unique_together={('period', 'campus', 'category', 'scope_label', 'is_biogenic')},
        ),
    ]
